### ISSUE TITLE
Body of Message is null in SubscriptionClient.RegisterMessageHandler Func Handler

### ISSUE THREAD

**Issue by bmmathe** [Azure/azure-service-bus-dotnet#123] opened 2017-04-10 22:09 UTC
## Actual Behavior
message.Body is null in the SubscriptionClient.RegisterMessageHandler func.  The UserProperties are loaded properly but not the body.

## Expected Behavior
I would expect the body to be the message contents.

## Versions  
- OS platform and version: Windows
- .NET Version: Core 1.1
- NuGet package version or commit ID: preview 2

**Comment by jtaubensee** [comment] 2017-04-10 22:12
Is this the same as #114? i.e. Are you sending messages with the older Service Bus client, and receiving them with this client?

**Comment by bmmathe** [comment] 2017-04-10 22:18
`<package id="WindowsAzure.ServiceBus" version="3.4.2" targetFramework="net452" />`

**Comment by jtaubensee** [comment] 2017-04-10 22:20
Ok, this is a duplicate of #114 then. We have a PR in review to fix this. #118

**Closed by jtaubensee** 2017-04-10 22:20 UTC
Labels: duplicate

**Comment by brettataarons** [comment] 2017-04-11 13:44
Is the full framework client considered old even if I'm using the latest version to publish to a topic? I updated the package to the latest 4.0.0 build and I still can't read the body using this client.

**Comment by bmmathe** [comment] 2017-04-11 14:49
I see my issue I think.  In my case we are posting JSON to the message body with a Content-Type set.  I think the goals of this client is to only work with byte[] messages?

**Comment by jtaubensee** [comment] 2017-04-11 18:30
@brettataarons - By "old" I mean the .NET Framework NuGet Package `WindowsAzure.ServiceBus` that you are using in combination with this library. Sorry for the confusion, I only say that because eventually that client will be replaced by this one (way off in the future).

But yes, using any version of that client would have caused this problem. This has been fixed for the next release.

**Comment by uhaciogullari** [comment] 2019-03-06 16:22
For the people who end up here; this is the solution:

```
using Microsoft.Azure.ServiceBus.InteropExtensions;

var body = message.GetBody<byte[]>();
```

**Comment by rmccabe24** [comment] 2019-03-22 09:59
Thanks for leaving that code @uhaciogullari - that was a massive help and worked straight away for us!  We were sending messages from an old app using the .net Framework (with an old Service Bus SDK) to a new app for consumption which was using the new .net Standard SDK within a .net Core application.

Thanks again!
