### ISSUE TITLE
Method for getting list of multiple subscription client

### ISSUE THREAD

**Issue by KhushbooSinha01** [Azure/azure-service-bus-dotnet#346] opened 2017-10-06 18:23 UTC
## Actual Behavior
Want to get list of service bus subscription clients of the single topic in .netCore same as getting in framework. 

## Expected Behavior
want to get multiple subscription clients list for the single topic in .netcore

## Versions  
- OS platform and version: windows 10
- .NET Version: 2.0 standard
- NuGet package version or commit ID:1.0.0

**Comment by nemakam** [comment] 2017-10-07 00:58
This is a duplicate of #65.
Implementing management operations should take care of this.

**Closed by nemakam** 2017-10-07 00:58 UTC
