### ISSUE TITLE
Do you guys have any release date for dynamically create topic using Microsoft.Azure.Management.ServiceBus 

### ISSUE THREAD

**Issue by LilanMadusankaSilva** [Azure/azure-service-bus-dotnet#380] opened 2017-12-04 08:18 UTC
I need to create azure topic & subscription programmatically (.net core). So have you guys plan to do that ? any plan release date?

**Comment by SeanFeldman** [comment] 2017-12-04 14:23
@LilanMadusankaSilva see #65.

**Comment by SeanFeldman** [comment] 2017-12-11 16:10
@LilanMadusankaSilva could you please close this issue in favour of #65? Thank you.

**Comment by nemakam** [comment] 2017-12-30 00:31
Duplicate of #65

**Closed** 2017-12-30 00:31 UTC
