### ISSUE TITLE
Java Deserialization adds additional content to message

### ISSUE THREAD

**Issue by riccardobecker** [Azure/azure-service-bus-dotnet#178] opened 2017-06-09 10:17 UTC
Hi all,

we experience issues in our IT landscape where there are .NET and Java components.

## Actual Behavior
1. On the .NET side we use the latest preview SDK which exposes a Message instead of the "old" BrokeredMessage.
2. Adding a payload to this body works fine and using a tool like service bus explorer or using our on C# codebase is perfectly able to deserialize this Message into a JSON string.

## Expected Behavior
1. The Java SDK we use still uses the BrokeredMessage style implementation.
2. The result of the message is an InputStream and getting the string value of this InputStream results in the original JSON payload but additional information is added.
The result in Java of looks like:

@ base64Binar3http://schemas.microsoft.com/2003/10/Serialization/�N{<The original JSON payload>�} 

On the Java side we strip those additional contents to get the pure JSON but this feels awkward to do.

Is there a way to tackle this and do others have this issue as well??

Thanks in advance,
Riccardo Becker

**Comment by nemakam** [comment] 2017-06-09 18:21
Duplicate of #138 
@riccardobecker , this is a known issue and we are tracking it. 
Further updates on thread #138

**Closed by nemakam** 2017-06-09 18:21 UTC
