### ISSUE TITLE
QueueClient automatic lock renewals seem to fail silently leading to MessageLockLostException

### ISSUE THREAD

**Issue by rondelward** [Azure/azure-service-bus-dotnet#684] opened 2019-04-02 15:51 UTC
## Actual Behavior
1. Using QueueClient.RegisterMessageHandler with PeekLock, Autocomplete=false, MaxAutoRenewDuration= 2hrs (MaxLockDuration 5 minutes)
2. Long running process (over 15 minutes or so), loses lock and is unable to successfully complete message
3. When `CompleteAsync` is called, we receive a `MessageLockLostException`
4. Message is abandoned and can be picked up again (depending on MaxDeliveryCount)

## Expected Behavior
1. Using QueueClient.RegisterMessageHandler with PeekLock, Autocomplete=false, MaxAutoRenewDuration= 2hrs
2. The MessageLock is renewed automatically for long running processing so that a message can be locked for as long as is needed for the processing to complete
3. Calling `CompleteAsync` removes the message from the queue

## Versions  
- OS platform and version: Windows 10/Windows Server 2012
- .NET Version: .NET Framework 4.6.1
- NuGet package version or commit ID: 
**Microsoft.Azure.ServiceBus:** 3.1.0
**Microsoft.Azure.Amqp:** 2.3.0

Also reproducible after updating the packages to
**Microsoft.Azure.ServiceBus:** 3.4.0
**Microsoft.Azure.Amqp:** 2.4.2

## Detailed Steps

Our code is rather simple and looks like this:
```
_queueClient.RegisterMessageHandler(
                    async (message, token) =>
                    {
                        try
                        {
                            processMessage(message); // await Task.Delay(...)
                            await _queueClient.CompleteAsync(message.SystemProperties.LockToken);
                        }
                        catch (Exception ex)
                        {
                            await _queueClient.DeadLetterAsync(message.SystemProperties.LockToken);
                        }
                    },
                    new MessageHandlerOptions(OnException)
                    {
                        AutoComplete = false,
                        MaxConcurrentCalls = MaxConcurrentCalls,
                        MaxAutoRenewDuration = MaxAutoRenewDuration
                    }
                );

```

`ProcessMessage` is the bit that can take quite a long time. The default LockDuration is 5 minutes and MaxAutoRenew is set to 2 hours for extremely long running messages. The majority of messages can be processed in a few seconds but we've noticed that any that take longer than 15 minutes are so fail 100% of the time. Some messages take up to an hour before attempting the `CompleteAsync` call

My first thought was that the locks simply were not being renewed at all but using PerfView I was able to confirm that the `RenewLock` operations are being called as I would expect. For reproduction purposes, I set the lock duration to 30 seconds and simulated a long running process with a `Task.Delay`. (I have the .etl trace available if that would assist in pinpointing the issue). Shorter runs are able to extend the locks (up to 5 minutes without issues), but the long running ones seem to fail. I'm not sure what the exact threshold is but seems to be above 15 minutes.

In my trace, there are no exceptions captured up until the 1st `MessageLockLostException`. The only weird thing (from my point of view at least) is that after the `CompleteAsync` is started, a new `AmqpGetOrCreateConnection` event is fired. My current theory is that even because the connection is mostly idle, (no other messages received while the processing is happening), the AMQP connection is lost (or times out perhaps) and the `RenewLock` calls are silently failing. I can see them being called every 19 seconds but no related exceptions. 

- Is this expected behavior or indeed a bug?
- Should we instead use `ReceiveAndDelete` for processing that passes a certain threshold instead of `PeekLock` as a best practice? This is the path we are considering as a workaround but first want to rule out configuration/client setup issues. 

Let me know if you have any suggestions.

**Comment by SeanFeldman** [comment] 2019-04-03 03:12
Is this a duplicate of #645?

**Comment by rondelward** [comment] 2019-04-04 02:02
@SeanFeldman This does seem very closely related to that issue. Since that question mentioned `MessageReceiver` specifically, I wasn't positive that it was same issue I was seeing with `TopicClient`. 

I'll add myself as a watcher to the other issue so this one can be closed as a dupe. Thanks!

**Closed as completed** 2019-04-04 02:04 UTC
