### ISSUE TITLE
I get MessageLockLostException when having multiple consumers of the same subscription of a topic

### ISSUE THREAD

**Issue by erickbp** [Azure/azure-service-bus-dotnet#523] opened 2018-06-29 16:56 UTC
## Actual Behavior
1. I have 2 consumers of the same subscription
2. It seems that the some messages are delivered to both consumers so when the last one tries to release the lock I get the exception with message: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue, or was received by a different receiver instance.
`await subscriptionClient.CompleteAsync(message.SystemProperties.LockToken);`

## Expected Behavior
1. competing consumer pattern: the message only delivered to one consumer

## Versions  
- OS platform and version: Microsoft Windows 10 Pro	10.0.17134 Build 17134
- .NET Version: 4.6.1
- NuGet package version or commit ID: Microsoft.Azure.ServiceBus 3.0.2

**Comment by nemakam** [comment] 2018-06-29 18:20
@erickbp 
I don't completely understand your question. Maybe the jargon is different.
Are you saying that a single message is received by more than one receiver? 
How far apart are the two receives? 
There can be multiple reasons why a lock on service can be lost - service broker machine restart / the lock actually expired. In the latter case, you are expected to `renew` the message yourself and ensure the lock isn't lost. For the former case, you are also expected to take care of it in your business logic. It is an atleast-once delivery system.

**Comment by nemakam** [comment] 2018-06-29 18:24
Also, FYI, the message can be completed only on the receiver it was received from.

**Comment by remcoongit** [comment] 2018-06-29 18:29
Please see: https://github.com/Azure/azure-service-bus-dotnet/issues/524  as initial code I used.

It looks like I'm having a similar issue with different way of using this package.

I create about 30 MessageReceivers with each max 3 concurrent threads processing messages from one MessageReceiver. The moment I complete the message I get the following (sometimes!):

The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue, or was received by a different receiver instance.   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<DisposeMessagesAsync>d__97.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<CompleteAsync>d__66.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)

When adding another SemaphoreSlim(1) to lock the complete operations; no errors. Also it only happens with high amounts of concurrent message-processing.

**Comment by erickbp** [comment] 2018-06-29 18:46
@nemakam Take a look, it's a very simple modification to the sample code from your team. Sometimes ProcessMessagesAsync1 and ProcessMessagesAsync2 are receiving the same message. 2 messages out of 10 messages.
[code on github](https://github.com/erickbp/sbtopic2018)

**Comment by nemakam** [comment] 2018-06-29 19:11
@erickbp 
I tried your code and not a single exception. I increased the message count to 200 and let it run, and I even changed the maxConcurrent messages to 5. 
We have long running tests that run everyday with lot of different combinations and we don't run into this issue much. Could you try running on a different machine?

**Comment by remcoongit** [comment] 2018-06-29 19:14
@erickbp 
Wild guess but;  Ensure the time on your PC is in sync with Azure (MS timeserver)

**Comment by erickbp** [comment] 2018-06-29 19:32
@nemakam 
I have just tried on a different machine and the result was the same.
Time on the PC is configured to automatic, so Windows is handling that part and as far as I can tell it looks fine.
Did you remove this line from my sample code?
`await Task.Delay(5000, token);`
If you remove it the problem does not happen.

**Comment by erickbp** [comment] 2018-06-29 19:40
@nemakam 
Interesting, if I increase MaxConcurrentCalls to 5 on both RegisterOnMessageHandlerAndReceiveMessages I don't get any exception either but if I run the code exactly as I have it on github I do see the exceptions.
Have you tried it with no modification at all?
Thank you

**Comment by nemakam** [comment] 2018-06-29 19:40
Tried with and without that. No repro... Tried the exact code as well and dont' get a repro..
Do you get any exception on ExceptionHandler?
Could you also try creating a new topic/sub and see if it still repros?

**Comment by nemakam** [comment] 2018-06-29 19:42
The other thing I can think of is your DefaultLockTimeout on the entity is set to 5 seconds.. What's the value set on the entity?

**Comment by erickbp** [comment] 2018-06-29 19:45
Lock duration: 30 seconds

**Comment by erickbp** [comment] 2018-06-29 19:51
@nemakam 
I created a new Service Bus namespace, topic and subscription and the problem persists.
Yes, the exceptions I'm seeing are on the ExceptionHandler. Here is an example:
`Message handler encountered an exception Microsoft.Azure.ServiceBus.MessageLockLostException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. Reference:cb546451-e735-41a0-9267-31da7e021b7d, TrackingId:a9bb889b0002000f002cea2d5b368cfe_G17_B3, SystemTracker:test201809:topic:mytopic~239|mysub, Timestamp:6/29/2018 7:48:51 PM
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<DisposeMessagesAsync>d__100.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<CompleteAsync>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ConsoleApp1.Program.<ProcessMessagesAsync2>d__10.MoveNext() in C:\Users\erick\Desktop\ConsoleApp1\ConsoleApp1\Program.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.MessageReceivePump.<MessageDispatchTask>d__13.MoveNext().`

**Comment by remcoongit** [comment] 2018-06-29 19:59
@erickbp @nemakam 

I am able to reproduce with your code. After running it a few times I get the same error as above. First 3 tries it works fine without any issues.

Could it be an Azure Service Bus issue? I also see in the logs from my other client (my code) the same lock issue... now its gone again and works fine.

**Comment by erickbp** [comment] 2018-06-29 20:03
@remcoongit thanks for trying it. BTW, it happens every time I try my sample code, not a single time goes with no error (as long as I run the code exactly as it is in the repo)

**Comment by remcoongit** [comment] 2018-06-29 20:05
I ran it another 5 times and with concurrency: 20 and 5000 messages.  No errors... this is strange.

**Comment by erickbp** [comment] 2018-06-29 20:07
@remcoongit yes, if I change MaxConcurrentCalls then it works fine for me too, so yes, it is definitely strange.

**Comment by nemakam** [comment] 2018-06-29 20:40
This is interesting.. Could you enable logging and repro the issue and share the logs with me? The ETW traces are emitted with event source "Microsoft-Azure-ServiceBus"

**Comment by remcoongit** [comment] 2018-06-29 21:22
How do I enable logging? Just the trace log?

I have more strange issues now.. My messages are being deadlettered automatically when no app is running.  I believe Azure is having issues or I need sleep... will test tomorrow.

**Comment by remcoongit** [comment] 2018-07-02 10:53
I'm not able to reproduce anymore. @erickbp  are you?

**Comment by erickbp** [comment] 2018-07-03 13:02
@remcoongit yes, I have just tried and it still happens.

**Comment by SeanFeldman** [comment] 2018-07-03 16:58
@erickbp I tried your code and everythign works as expected
![image](https://user-images.githubusercontent.com/1309622/42233844-e280e3e6-7eaf-11e8-923b-6e059355df10.png)

Can you try another namespace/environment you're running this from? For example, running this from an Azure VM rather than your environment.

**Comment by nemakam** [comment] 2018-07-03 18:11
@erickbp 
If you are still able to repro, please capture the logs the way I described above and share it with us.

**Comment by erickbp** [comment] 2018-07-06 02:52
@nemakam I will try it when return from vacation, thanks for your help

**Comment by Hyjaz** [comment] 2018-07-09 15:53
Regarding the cancellation token, how does one use it to cancel a message?
If I do not complete the message, does it get cancelled automatically?
Do I need to abandon it?
Is the cancellation token only on the SubscriptionClient?

If this issue is not the right place for this I will create another issue.

**Comment by macpak** [comment] 2018-07-15 10:31
@SeanFeldman I also get this error (both on our PROD env and using the example mentioned above). I was experimenting with the setup, and when I set the "Lock duration" property of a subscription to 59s,  I do not get it. However, when I decrease it, say to 30s, I get the error.

**Comment by SeanFeldman** [comment] 2018-07-16 01:29
Do you have a prefetch enabled @macpak? And what's the processing time? 30 seconds is a lot of time.

**Comment by macpak** [comment] 2018-07-16 05:48
@SeanFeldman No, a prefetched is disabled. Generally, I used the code provided by @erickbp  to reproduce the issue.

**Comment by DanCaveman** [comment] 2018-09-13 19:06
I am seeing this same issue, but instead of calling receiver.ReceiveAsync, I am creating multiple receivers and registering a handler.  I assume under the covers it is doing something similar. I made the number of receivers controlled by configuration.  When I have more than one receiver (usually use 5 or so), I get these exceptions.  When I change the configuration to use a single receiver, I do not get any errors.

Is there any solution to this yet?

**Comment by SeanFeldman** [comment] 2018-09-13 21:12
I would suggest sharing repros.

1. By just describing the problem you're forcing anyone who'd look into double the time (time on re-building your scenario hoping it's accurate and then time to search for the problem).
1. Little nuances can skew results. Having a repro is an exact replica of the problem, no deviations in code.

**Comment by axisc** [comment] 2019-04-17 19:13
Closing this for now, please reopen if you still see this issue.

**Closed by axisc** 2019-04-17 19:13 UTC
