### ISSUE TITLE
Calling SendAsync hangs in an ASP.NET MVC application

### ISSUE THREAD

**Issue by mss37** [Azure/azure-service-bus-dotnet#287] opened 2017-08-21 20:55 UTC
## Actual Behavior
1. Create a client
2. Call queueClient.SendAsync
3. Wait for the response, it hangs forever.

## Expected Behavior
1. Create a client
2. Call the SendAsync method
3. Wait for the response.
4. The call finishes, and the message is added to the queue.

## Versions  
- OS platform and version: win 10
- .NET Version: .NET 4.7
- NuGet package version or commit ID:1.0.0

**Comment by vinaysurya** [comment] 2017-08-21 21:58
@mss37, I tried writing a sample DotNet console application, using the 1.0.0 library and with 4.7 as DotNet TargetFramework and it worked fine for me. To isolate connectivity issues etc, can you please try a simple DotNet Console application and see if that works?

**Comment by SeanFeldman** [comment] 2017-08-21 23:45
@mss37 I highly recommend to supply a repro code that can be executed/debugged when reporting an issue like this. #284 could be a good explanation why it's so helpful 🙂

**Comment by SimonCropp** [comment] 2017-09-11 23:41
@mss37 out of curiosity does it hang if u include a `.ConfigureAwait(false)`?

**Comment by mss37** [comment] 2017-09-17 06:02
@SimonCropp yes, it hangs as well, one thing might be interesting, is that I need to deal with multiple queues at the same time, so I create many message receivers/queue clients at the same time for these different queues.

**Comment by nemakam** [comment] 2017-09-18 19:54
@mss37 It would still be easier if you could provide a sample code on how you are using this library? Also, what about this?
> To isolate connectivity issues etc, can you please try a simple DotNet Console application and see if that works?

**Comment by cmckeegan** [comment] 2017-09-20 16:13
I see the same issue whenever I call MessageSender.SendAsync from within a ASP.NET web api. Note that the exact same code works if its a AspNet Core webapi. Both are running on NetFx 4.6.2 hosted inside IIS Express.

```
public void Post([FromBody] string text) 
{
	var sender = new MessageSender(connectionString, queueName);
	var msg = new Message(Encoding.UTF8.GetBytes(text));

	sender.SendAsync(msg).ConfigureAwait(false).GetAwaiter().GetResult();
}
```

**Comment by SimonCropp** [comment] 2017-09-20 20:35
Isnt sender meant to be scoped as “instance per appdomain”. Can u try putting that in a static variable? Also if that method is calling an async api then ideally it should also be async, and avoid the getawaiter code

**Comment by cmckeegan** [comment] 2017-09-21 08:47
Thanks for the response @SimonCropp I hadn't any guidance to that effect, but making the sender static makes no difference. Making the action method async does work, but unfortunately in my real scenario I need the call to complete synchronously.

**Comment by SimonCropp** [comment] 2017-09-22 00:27
@cmckeegan what web framework are you using that does not support async?

**Comment by cmckeegan** [comment] 2017-09-22 13:13
@SimonCropp Its ASP.NET WebApi so it supports async fine, but I'm attempting to add the service bus a few layers into some legacy code which has no async. Its not a greenfield project so I do have to work within this.

Is a deadlock on waiting for the Task expected behaviour in ASP.NET WebApi?

**Comment by clemensv** [comment] 2017-10-06 08:41
I do wonder what task scheduling "magic" inside ASP.NET may be at work here. Our "send" operation is a combination of a transfer and waiting for an acknowledgement for that transfer, so there several network interactions, and they might be concurrent. Synchronous ASP.NET contexts are quirky.

Can you try out the nested task tricks here on the SO post, @cmckeegan, and see whether that unblocks you for the moment?

https://stackoverflow.com/questions/31237989/calling-3rd-party-web-api-from-my-web-api-hang 

We clearly have to find some clean option prevent that from deadlocks becoming an issue on sync ASP.NET or UX  contexts, so I'll leave this open as an investigation item, even though it seems like it's not a bug in all-async environments.

**Comment by cmckeegan** [comment] 2017-10-11 16:08
Thanks for the response @clemensv I ended up using a workaround from the following Stephen Toub article:

https://blogs.msdn.microsoft.com/pfxteam/2012/04/13/should-i-expose-synchronous-wrappers-for-asynchronous-methods/ 

specifically the _Offload to Another Thread_ advice.

**Comment by nemakam** [comment] 2017-10-12 22:03
@mss37, Take a look at the workarounds suggested by @cmckeegan. 
Closing this issue for now. Reopen if not solved.

**Closed by nemakam** 2017-10-12 22:03 UTC
