### ISSUE TITLE
MessageReceiver.ReceiveAsync is not returning the correct number of messages

### ISSUE THREAD

**Issue by ssashok10** [Azure/azure-service-bus-dotnet#469] opened 2018-05-23 20:23 UTC
## Actual Behavior
1. MessageReceiver.ReceiveAsync(batchSize) is not receiving all the messages from Topic subscription when "partition" is enabled.  This method returns correct number of messages when the Topic "partition" is not enabled.

## Expected Behavior
1. MessageReceiver.ReceiveAsync(batchSize) should receive the correct number of messages which is equivalent to "batchSize" even when the Topic is enabled for "partition".

## Versions  
-  Windows 7
- .NETCore.Platforms(2.0.2)

**Comment by nemakam** [comment] 2018-05-24 03:01
Duplicate of #441

**Closed by nemakam** 2018-05-24 03:01 UTC
Labels: duplicate
