### ISSUE TITLE
Can we create topic subscription problematically using .net core 2

### ISSUE THREAD

**Issue by LilanMadusankaSilva** [Azure/azure-service-bus-dotnet#379] opened 2017-11-29 07:32 UTC
Can we do that using .net core 2 or standard 2 ?

**Comment by SeanFeldman** [comment] 2017-11-29 07:34
Duplicate of #65.
More details: https://github.com/Azure/azure-service-bus-dotnet/issues/65#issuecomment-338874419

**Closed** 2017-11-29 07:46 UTC
