### ISSUE TITLE
Unable to Complete Message when processes takes more than 10 minutes

### ISSUE THREAD

**Issue by NiklasArbin** [Azure/azure-service-bus-dotnet#406] opened 2018-01-17 13:42 UTC
## Actual Behavior
1.  Calling CompleteAsync hangs the application. Async deadlock?

## Expected Behavior
1.  Calling CompleteAsync completes the message or throws

## Versions  
- OS platform and version: Windows 10 Pro
- .NET Version: net461 and netcore2
- NuGet package version or commit ID: NuGet Microsoft.Azure.ServiceBus 2.0.0 and 3.0.0-preview-01

```csharp
class Program
    {
        private static QueueClient _queueClient;

        static void Main(string[] args)
        {
            string connectionString = "Endpoint=sb:/some-namespace.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=";
            string path = "a-queue";
            _queueClient = new QueueClient(connectionString, path, ReceiveMode.PeekLock, RetryPolicy.Default);
            _queueClient.RegisterMessageHandler(Handler, new MessageHandlerOptions(ExceptionReceivedHandler)
            {
                AutoComplete = false,
                MaxAutoRenewDuration = TimeSpan.FromMinutes(20),
                MaxConcurrentCalls = 1
            });

            Console.ReadLine();
        }

        private static Task ExceptionReceivedHandler(ExceptionReceivedEventArgs exceptionReceivedEventArgs)
        {
            Console.WriteLine("Error message");
            return Task.CompletedTask;
        }

        private static async Task Handler(Message message, CancellationToken cancellationToken)
        {
            Console.WriteLine("Received message");
            await Task.Delay(TimeSpan.FromMinutes(10)).ConfigureAwait(false);
            Console.WriteLine("Completing message");
            await _queueClient.CompleteAsync(message.SystemProperties.LockToken).ConfigureAwait(false); //Hangs here
            Console.WriteLine("Completed message"); //Never called
        }
    }
```

**Comment by nemakam** [comment] 2018-01-17 20:16
Duplicate of #378

**Closed by nemakam** 2018-01-17 20:16 UTC
