### ISSUE TITLE
QuotaExceededException

### ISSUE THREAD

**Issue by johnknoop** [Azure/azure-service-bus-dotnet#237] opened 2017-07-27 12:04 UTC
I started my console app two days ago, and have since then received no more than 4 messages. Yet today, I get this exception:

> Session handler exception "Microsoft.Azure.ServiceBus.QuotaExceededException: Cannot allocate more handles. The maximum number of handles is 4999.

I'm not sure what kind of handles it is referring to, but to imagine that I would have exceeded some form of quota after this little activity seems wrong.

**Comment by nemakam** [comment] 2017-07-27 18:11
@johnknoop , could you provide a sample code that repro's this issue? How are you using service bus? Is it Queues or Topics? Is sessions enabled on the entity?

**Comment by SeanFeldman** [comment] 2017-07-27 18:12
:+1: for a repro.
Wouldn't be able to assist w/o having more context.

**Comment by johnknoop** [comment] 2017-07-27 18:27
Hi

Here's my code:

```
			queueClient.RegisterSessionHandler(async (session, message, cancel) =>
			{
				var greeting = message.Body.As<Greeting>();
				logger.Information($"Saving greeting from session {session.SessionId} with message {greeting.Message}...");
				
				await SaveGreeting(greeting);
				await session.CompleteAsync(message.SystemProperties.LockToken);
			}, exceptionEvent =>
			{
				logger.Information("Session handler exception {exception}", exceptionEvent.Exception);
				return Task.CompletedTask;
			});

		    while (true)
		    {
			    Console.ReadKey(true);
		    }
```

Thats it.

John

**Comment by nemakam** [comment] 2017-07-27 18:30
@johnknoop , Did you receive any exception event these two days?

**Comment by johnknoop** [comment] 2017-07-27 18:46
No, only today. I sent two messages this morning. Both were received and saved but the exception was logged as well.

**Comment by nemakam** [comment] 2017-07-27 22:44
This must be a manifestation of https://github.com/Azure/azure-amqp/pull/68 .
Older links that were created were not cleaned up. Once that PR is completed and a new version is released, this should be taken care automatically.

**Comment by paulb2011** [comment] 2017-08-09 10:34
I'm seeing this exception as well with version 4.1.3:

I have a service which sends an event every 5 minutes, 24 hours a day, after about a week I started seen this exception:

Microsoft.ServiceBus.Messaging.QuotaExceededException: Cannot allocate more handles to the current session or connection. The maximum number of handles allowed is 4999. Please free up resources and try again., referenceId: 0bff6627c9bc4c5fb40addea5e410c8e_G8

**Comment by vinaysurya** [comment] 2017-08-11 18:58
@paulb2011, this github is only tracking issues for the new `Microsoft.Azure.ServiceBus` library. The issue you are referring to is from the old `WindowsAzure.ServiceBus` client library. Can you please create a new issue in this repo(https://github.com/Azure/azure-service-bus/issues) and we will triage and fix with the next release of that library

**Comment by vinaysurya** [comment] 2017-08-11 18:59
@johnknoop, Can you confirm if the issue is fixed for you with the new version of this library. If so, we can close this issue.

**Comment by johnknoop** [comment] 2017-08-11 21:35
Hi @vinaysurya 

Unfortunately I haven't been able to do that, due to an issue with Visual Studio Team Services currently. But I'll close this issue for now, assuming it will be fixed. Otherwise I'll re-open.

Thanks

**Comment by johnknoop** [comment] 2017-09-04 07:56
FYI I've now been able to deploy a new version of the program. I'm now running the 1.0 version of this library. I'll start publishing a message every day and see if/when the consumer program stops/crashes.

**Comment by johnknoop** [comment] 2017-09-06 09:21
Hi

So, today it happened again. I deployed a container with this code running on the 1.0 version of the lib the day before yesterday. Since then I've been sending messages a random times from my local computer and verify in the log that they get handled correctly. But just now when I did the same routine, I find this in the log:

"Microsoft.Azure.ServiceBus.QuotaExceededException: Cannot allocate more handles. The maximum number of handles is 4999

**Comment by johnknoop** [comment] 2017-09-06 15:16
This is the usage of the queue, btw:
![image](https://user-images.githubusercontent.com/3394270/30119783-1c1baa2a-9327-11e7-885d-b9676071d75f.png)

**Comment by SeanFeldman** [comment] 2017-09-06 16:28
According to the documentation, `QuotaExceededException` would be thrown in 2 cases
> The messaging entity has reached its maximum allowable size, or the maximum number of connections to a namespace has been exceeded.

Looks like it's the second issue (connections) and not the entity size.

The [snippet](https://github.com/Azure/azure-service-bus-dotnet/issues/237#issuecomment-318446939) is taken out of the context that could influence how things are set up. @johnknoop any chance to share a repro that could be fully examined?

**Comment by johnknoop** [comment] 2017-09-06 16:44
Sean,

Here is a gist containing my project: https://gist.github.com/johnknoop/47488ea2c0e011f0fa1e5a2cd39b1a80

The deployment process starts the program without any arguments, which registers a session handler. Then once every day I run the same program locally, but with arguments "publish XXX SomeMessage" where XXX will be used as the SessionId.

**Comment by johnknoop** [comment] 2017-09-07 15:55
Note: I'm not using my service bus for anything other than this, so it can't really be a matter of any quota being exceeded in terms of size neither connections.

**Comment by SeanFeldman** [comment] 2017-09-11 04:26
@johnknoop I don't see anything obviously wrong.
I'll defer to @Azure/azure-service-bus-write 🙂

**Comment by johnknoop** [comment] 2017-09-11 07:38
@SeanFeldman I'm not really sure what that means :) Do I need to do anything?

**Comment by nemakam** [comment] 2017-09-11 18:17
@johnknoop @SeanFeldman, I didnt get a chance to take a look at this yet, but its on my list. Will work on it soon..

**Comment by johnknoop** [comment] 2017-09-11 19:07
@nemakam That would be super helpful.

He're are some more information I was able to extract from the docker container log:

> INF Subscribing to queue greetingsqueue
2017-09-04 07:52:39 INF Saving greeting from session 34 with message Gomorron...
2017-09-04 07:52:42 INF Message handled!
2017-09-04 12:12:37 INF Saving greeting from session 34 with message Menhejsan...
2017-09-04 12:12:38 INF Message handled!
2017-09-05 06:58:43 INF Saving greeting from session 341 with message 1709050858...
2017-09-05 06:58:43 INF Message handled!
2017-09-06 04:19:02 INF Session handler exception "Microsoft.Azure.ServiceBus.QuotaExceededException: Cannot allocate more handles. The maximum number of handles is 4999.\n   at Microsoft.Azure.ServiceBus.SessionClient.<AcceptMessageSessionAsync>d__34.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.ServiceBus.SessionReceivePump.<SessionPumpTaskAsync>d__20.MoveNext()"
2017-09-06 04:20:02 INF Session handler exception "Microsoft.Azure.ServiceBus.QuotaExceededException: Cannot allocate more handles. The maximum number of handles is 4999.\n   at Microsoft.Azure.ServiceBus.SessionClient.<AcceptMessageSessionAsync>d__34.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Microsoft.Azure.ServiceBus.SessionReceivePump.<SessionPumpTaskAsync>d__20.MoveNext()"

It does indeed appear to be the number of handles that maxes out, altough I cannot for the life of me understand why.

Let me know if theres anything more I can assist with, like access to the service bus namespace or whatever.

**Comment by johnknoop** [comment] 2017-09-18 16:58
@nemakam I'm seeing in your pull request that the problem occurs when a link cannot be created. Is that something that regularly happens in AMQP, or does it indicate that something might be wrong on my end?

**Comment by nemakam** [comment] 2017-09-18 18:02
@johnknoop Its a very expected scenario. When you call `AcceptMessageSession`, we try to open a link for a particular `MessageSession`. If no sessions exist on the backend, the `link.Open()` ends up throwing. At this time, link is not established, but we have already established an `amqp-session` to open this link. So we are supposed to manually close these opened sessions, which is #325. 
If we don't close it, after 5000 failed `AcceptMessageSession` calls, we will start throwing `QuotaExceededException` since there are 5000 opened sessions in the backend.

**Closed** 2017-09-18 18:03 UTC
Labels: bug
