### ISSUE TITLE
QueueClient.RegisterMessageHandler -- no way to timeout if no messages are received

### ISSUE THREAD

**Issue by CodeCharm** [Azure/azure-service-bus-dotnet#177] opened 2017-06-09 04:07 UTC
Maybe I'm approaching this wrong? I'm a little new to this library; please direct me to what docs/posts I missed if I am thinking about this the wrong way.

`QueueClient.RegisterMessageHandler` blocks until a message is received. It's not awaitable; it doesn't return a `Task`.

I would like to establish a timeout in case there are no messages to receive. But it seems to drop into the message pump and doesn't return unless I have AutoComplete = true, or set the CancellationToken from within the loop, neither of which helps if I never get a message.

Consequently, there's no simple way to timeout that I can see. I'll have to wrap the call in a `Task.Run`, then use a `Task.WhenAny` with a `CancellationToken` (or something, I don't know yet). It feels wrong. Especially because the inner `MessageReceiver` uses a Task in `OnMessageHandlerAsync` while waiting for the message to get to the `MessageReceiverPump`.

I'm suggesting this be added as a feature, and I'm willing to try to make a contribution to do it, but I don't want to waste anyone's time.

My thought was to use the `ReceiveTimeOut` property in the `MessageHandlerOptions`, and use a `CancellationTokenSource` in the `OnMessageHandlerSync` to break out after the delay, but then throw a `TimeoutException` if it was the delay that broke out of the awaiter.

**Comment by SeanFeldman** [comment] 2017-06-09 05:27
`QueueClient.RegisterMessageHandler` is a message pump. It's purpose is to continuously run and invoke a handler provided by you for each incoming message, not process a single message and be done.

It sounds what you want to do is to receive a single message with a timeout. For that you have [`QueueClient.ReceiveAsync(TimeSpan serverWaitTime)`](https://github.com/Azure/azure-service-bus-dotnet/blob/6cc56bda017d28737b1eae47124cd6d115bc2086/src/Microsoft.Azure.ServiceBus/Core/MessageReceiver.cs#L256). Is that what you're after?

**Comment by nemakam** [comment] 2017-06-09 19:22
Every thing that @SeanFeldman mentioned is right, except for a small typo...
The `ReceiveAsync` is a method on `MessageReceiver` and not `QueueClient`. (The link is right though).

Closing this issue.

**Comment by CodeCharm** [comment] 2017-06-09 19:23
No, I wanted a message pump. It's just that I have no external control over when to end the message pump. Once I'm in it, I'm stuck in it until a message is received.

The ReceiveAsync solution would be part of a message pump that I would have to create on my own -- it'd be better/easier for me to fork a thread to run QueueClient.RegisterMessageHandler, and reset a timer whenever I receive a message.

**Comment by nemakam** [comment] 2017-06-09 19:45
@CodeCharm , Does #154 describe your issue or are you talking about a way to pause/stop the pump?

**Comment by CodeCharm** [comment] 2017-06-09 23:01
@nemakam It might be the same issue -- it certainly feels related. However, I am looking for some more control. As far as I can tell the `ReceiveTimeout` property of `MessageHandlerOptions` is unused; this seems like the ideal use for it. If @vinaysurya (from #154) hasn't already started work on it, I would be willing to give it a shot. I've already forked and run all the unit tests against my own SB to prepare...

**Comment by nemakam** [comment] 2017-06-09 23:38
> I still expect that the message pump itself is primarily responsible for gracefully exiting the pump if/when the expected message is received.

There seems to be a misunderstanding here (from either side). Message pump **doesn't** exit after receiving the message. Its always running as long as the actual `QueueClient` is open. Everytime it receives a message, it will invoke the function/handler that was passed to it. It is not expected to close before the lifetime of the `QueueClient`.

>  I would be willing to give it a shot. I've already forked and run all the unit tests against my own SB to prepare...

That would be appreciated. Let us know if you need any help. 
But at the same time, keep in mind the point I just mentioned above. I am still unclear on the exact requirements that you need.

**Comment by CodeCharm** [comment] 2017-06-09 23:48
That's what I thought! But I agree with #154, one minute can be too long to wait for a message that is never received. It just kills my console client.

I was under the impression that the CancellationToken passed into the message handler should be used by the handler to notify the pump that it should exit the pump. What's that CancellationToken for, if not that?

**Comment by nemakam** [comment] 2017-06-10 00:07
So the expected behavior is that calling `RegisterMessageHandler` should return immediately and in a background thread this pump should invoke the user provided function on every message. The bug in #154 is that this method doesn't return immediately and ends up waiting for a minute if there are no messages in the queue. 

The cancellation token is used here for an entirely different reason. Like I mentioned, this pump works forever as long as `QueueClient.CloseAsync()` is not called. When `CloseAsync()` is called, then this `cancellationToken.Cancel()` is invoked to inform the background Pump thread to stop pumping further messages. Additionally, the function that you provide can check for `CancellationToken.IsCancelled` to stop executing further.

**Comment by CodeCharm** [comment] 2017-06-10 01:34
That makes sense, and I'd be happy to try to close #154. Any specific guidance before I start?

**Comment by nemakam** [comment] 2017-06-10 01:56
I think it should be a pretty simple fix. Probably just updating `MessageReceivePump.StartPumpAsync` by passing a timeout of zero for the receive call might do the trick. Just do some testing and see if that fixes the issue.

**Comment by SeanFeldman** [comment] 2017-06-14 04:27
@CodeCharm I've started PR #183 to address this issue. 
@nemakam aside from smoke testing, should there be a test added to verify this fix or we're good with manual verification?

**Comment by CodeCharm** [comment] 2017-06-14 04:54
@SeanFeldman Awesome, thanks. I had started, but I had started by trying to make a new test, and got a little tangled in the test harness. LMK if I can help in any way.

**Comment by SeanFeldman** [comment] 2017-06-14 04:57
@CodeCharm if you could smoke test with the repro you got going, would be great. If you feel like adding an a test to the suite, please do (as a PR on top of this PR). 

Unless @nemakam comes and declares: 
![image](https://user-images.githubusercontent.com/1309622/27116004-b906a0bc-508b-11e7-8e10-638ce60a887e.png)

**Comment by CodeCharm** [comment] 2017-06-14 05:05
@SeanFeldman I will try that out -- but I can't get to it until tomorrow evening (PDT).

**Comment by SeanFeldman** [comment] 2017-06-14 05:07
​No rush. I'm in MST and it's time to count the stars.

**Comment by SeanFeldman** [comment] 2017-06-15 06:07
@CodeCharm added some tests.

**Comment by nemakam** [comment] 2017-06-15 21:26
#183 is checked in. Next release should solve this issue

**Closed by nemakam** 2017-06-15 21:26 UTC

**Comment by CodeCharm** [comment] 2017-06-16 06:00
@SeanFeldman @nemakam I confirmed from my fork and the code I'm writing against it that the fix works. Thanks!
