### ISSUE TITLE
Message Pump reports out ObjectDisposedException when message has been completed

### ISSUE THREAD

**Issue by adbre** [Azure/azure-service-bus-dotnet#388] opened 2017-12-14 09:13 UTC
## Actual Behavior
1. Register message handler in client with ReceiveMode.PeekLock and AutoComplete=True
2. Messages have been/are being enqueued
3. As messages are handled, *sometimes* a ObjectDisposedException is reported for ExceptionReceivedContext.Action "RenewLock"

## Expected Behavior
1. Register message handler in client with ReceiveMode.PeekLock and AutoComplete=True
2. Messages have been/are being enqueued
3. No ObjectDisposedException in RenewLock being reported

## Versions  
- OS platform and version: Microsoft Windows 10.0.15063
- .NET Version: 4.7 (460798)
- NuGet package version or commit ID: 2.0.0

## Comments
I belive this is a race condition as the error is only reported sometimes.
In some tests I can run 100 messages and get 4 errors, and some cases 1000 messages with 3 exceptions.

This issue is related to #361. And the edit suggested by @vinaysurya in https://github.com/Azure/azure-service-bus-dotnet/pull/362#issuecomment-339429840 would probably solve this.
But because the issue did not cover the same scenario and also because the PR has not got any attention lately I decided to open a separate issue anyways.

## Details

    {
        "Action": "RenewLock",
        "Endpoint": "REDACTED.servicebus.windows.net",
        "EntityPath": "REDACTED",
        "ClientId": "MessageReceiver5REDACTED"
    }

    System.ObjectDisposedException: The CancellationTokenSource has been disposed.
        at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
        at System.Threading.CancellationTokenSource.InternalRegister(Action`1 callback, Object stateForCallback, SynchronizationContext targetSyncContext, ExecutionContext executionContext)
        at System.Threading.CancellationToken.Register(Action`1 callback, Object state, Boolean useSynchronizationContext, Boolean useExecutionContext)
        at System.Threading.CancellationToken.InternalRegisterWithoutEC(Action`1 callback, Object state)
        at System.Threading.Tasks.Task.Delay(Int32 millisecondsDelay, CancellationToken cancellationToken)
        at System.Threading.Tasks.Task.Delay(TimeSpan delay, CancellationToken cancellationToken)
        at Microsoft.Azure.ServiceBus.MessageReceivePump.<RenewMessageLockTask>d__15.MoveNext()

**Comment by SeanFeldman** [comment] 2017-12-14 16:58
@adbre to clarify, what distinguishes this from #361 is that `ObjectDisposedException` is thrown during normal operation of message pump and not on shutdown?

**Comment by vinaysurya** [comment] 2017-12-14 18:58
@adbre, this is a duplicate of issue #361. Once that fix is checked in, you should not see this issue. 
@SeanFeldman, the issue#361 has some unresolved comments which when fixed would have resolved this issue as well. We'll try to get that checked in.

**Comment by SeanFeldman** [comment] 2017-12-14 19:13
👍 @vinaysurya Perhaps changing the title of #361 would help to state better what that issue is covering? 🙂

**Comment by adbre** [comment] 2017-12-14 19:28
Not identical. #361 states that the receiver should be closed.
In my case I have not closed it, but the exceptions still occur while
receiving messages from the queue.

But yes, they're very similar.

Den 14 dec. 2017 8:13 em skrev "Sean Feldman" <notifications@github.com>:

**Comment by vinaysurya** [comment] 2017-12-16 18:05
Fixed with pr https://github.com/Azure/azure-service-bus-dotnet/pull/390

**Closed by vinaysurya** 2017-12-16 18:05 UTC
