### ISSUE TITLE
Add transaction support for sessions/messaging

### ISSUE THREAD

**Issue by affandar** [Azure/azure-service-bus-dotnet#88] opened 2017-02-22 21:40 UTC
## Actual Behavior
System.Transactions is not present in dotnet core and hence the service bus dotnet core client does not support transactions.

## Expected Behavior
We would have some counterpart for System.Transactions.Transaction in the dotnet core world. 

## Versions  
All

**Comment by jtaubensee** [comment] 2017-02-22 21:58
Duplicate of #6

**Closed** 2017-02-22 21:58 UTC
Labels: duplicate, enhancement
