### ISSUE TITLE
HTTP proxy support in .NET Core/Standard

### ISSUE THREAD

**Issue by cocowalla** [Azure/azure-service-bus-dotnet#436] opened 2018-03-30 09:07 UTC
The documentation, [such that it is](https://github.com/Azure/azure-service-bus-dotnet/blob/9b31751a1c5ade61f353bd4905b0665ad0269dfa/src/Microsoft.Azure.ServiceBus/TransportType.cs), for proxy support seems to conflict with [this](https://github.com/dotnet/corefx/pull/11996) .NET Standard PR.

Is using an HTTP proxy supported when using transport `AmqpWebSockets` with .NET Core clients?

I'd like to use ASB from .NET Core clients running on Linux, but lack of HTTP proxy support is a deal breaker for me.

**Comment by nemakam** [comment] 2018-03-30 19:20
@cocowalla 
We have been waiting for .net 2.1 based on couple of fixes that were required for .net core (https://github.com/dotnet/corefx/issues/5120) . It looks like .net 2.1 is now released. Will need to test it with latest .net core and get back to you.

**Comment by cocowalla** [comment] 2018-04-22 10:26
@nemakam hi, any news on this?

**Comment by arthis** [comment] 2018-07-06 07:16
The dotnet core sdk 2.1 has been released for over a month now. Could we have any information/date about this issue now?

**Comment by nemakam** [comment] 2018-07-06 21:09
There is no additional work that needs to be done on the client side except for testing it to ensure it is working. It already works as expected on net46.
This library targets .net standard and not .net core. So even though .net core 2.1 is released, I cannot change the target version since .net standard 2.1 isnt released. 
Could you try to run this on your proxy enabled machine using .net core 2.1 application and let us know if it works?

**Comment by arthis** [comment] 2018-07-09 09:10
We are  currently trying to access the azure service bus  from behind an HTTP proxy with .net core applications. We have not seen anywhere how to handle the proxy settings in dot net core. 

With .net framework a simple reference in the app.config was enough to do the trick :

```
<system.net>
  <defaultProxy enabled="true">
   <proxy bypassonlocal="true"
          proxyaddress="http://proxy.domain.org:8888/" />
  </defaultProxy>
 </system.net>

```

How is it planned to handle it with the azure service bus library using dotnet core ?

PS  : I have cloned your repo and run the tests against my instance of azure service bus, and I have the same issues.

PPS : Yes I have tried building and testing using the latest sdk available 2.1.103

**Comment by arthis** [comment] 2018-07-31 12:00
Which library should I use to target .net core?

**Comment by gijsbertsyntess** [comment] 2018-08-14 11:17
Hi,

I tried your suggestion, by setting the default webproxy, like this:

```
WebProxy proxyObject = new WebProxy(
    "http://<proxyserver>:<proxyport>", 
    true, 
    new string[] { "somemachine" }, 
    new NetworkCredential("<user>", "<password>"));
WebRequest.DefaultWebProxy = proxyObject;
```

But unfortunately this didn't work for me.

The following did work, but it doesn't seem like an ideal solution to me:

`AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);`

**Comment by markvl2** [comment] 2018-08-23 02:04
Hi,

We have a ClientWebSocket proxy issue when connecting from my dev machine to a Cosmos DB in Azure via Gremlin.Net.

We are behind a proxy and when I run my code using .Net Framework (not .net core the older one) it works without an issue. As soon as I switch to .Net core and its implementation of Websockets it does not connect to Azure nor hit a breakpoint i have made where I set the proxy credential options I have configured. It seems to totally ignore the Options setting I have made in the code. I point the proxy at our internal proxy or at fiddler and neither shows this sockets call. We are going to have to revert back to non .Net core to get this to work :( 

It seems that that the .Net Core 2.1 implementation of the 
Systen.Net.WebSockets.ClientWebSocket.Options.Proxy
is being **completely** ignored by the ClientWebSockets code.

eg code 
    internal class WebSocketConnection : IDisposable
    {
        private const int ReceiveBufferSize = 1024;
        private const WebSocketMessageType MessageType = WebSocketMessageType.Binary;
        private ClientWebSocket _client;

        public async Task ConnectAsync(Uri uri)
        {
            _client = new ClientWebSocket();
  	    _client.Options.Proxy = new PHGProxy(); // TOTALLY IGNORED
            await _client.ConnectAsync(uri, CancellationToken.None).ConfigureAwait(false);
        }

Could anyone out there who knows this area of .Net core confirm if this is /is not implemented as its been quite the time wasting rabbit hole so far unfortunately.

Kind regards,

Mark

**Comment by nemakam** [comment] 2018-09-22 02:28
Since @markvl2 has confirmed proxy usage, I'm going to close this issue.
@markvl2 - could you please reply as to how you configured the default proxy settings?

**Comment by nemakam** [comment] 2018-09-24 21:45
@arthis 
> Reference some dotnet core fx issue at least, but do close it this way with no explanation.

As mentioned earlier, there is no fix that is required or feature work that needs to be done. Looks like latest 2.1 netcore has proxy implemented and the only thing pending is a verification that it indeed works. Take a look at this comment - https://github.com/Azure/azure-service-bus-dotnet/issues/436#issuecomment-377601501 

Setting `SystemProxy` is the only known way of setting the proxy. Could you try setting the system proxy (not `app.config`) and see if it works?

**Comment by 5w33n** [comment] 2018-10-18 21:08
Not sure if this is working - can you clarify the exact steps? Specifically, when you say seeing the system proxy, is that the value returned by the OS when using "netsh winhttp proxy"? 

If not, could you provide a small snippet of how we should be setting the system proxy please?

**Comment by sebhaub** [comment] 2019-01-17 15:54
@nemakam, @5w33n is there any update on this? 
I have a SystemProxy configured in Windows.
Working with net471 a connection using AMQPWebSockets is working through proxy but a switch to netcoreapp2.1 / netcoreapp2.2 results in no proxy being used. 

Any help appreciated.

**Comment by markvl2** [comment] 2019-01-17 19:55
When developing locally on my work pc and connecting to azure databases, service bus etc I need to have fiddler running to bypass the work proxy when using .net core 2.1 2.2

**Comment by sebhaub** [comment] 2019-01-18 13:52
@markvl2 thanks for the hint, with fiddler it also works here. Anyway i don´t understand this behaviour and how to address it in a way to avoid running this fiddler proxy. Can anyone help out here? 
I read that netcore pics up the WinINET proxy settings, so why is this not taking effect here if configured correctly?

**Comment by omniscient** [comment] 2019-02-15 22:02
I haven't seen a clear answer as to how we can configure the equivalent on a .NET Core web api so I'll offer my 2 cents.  On linux, deployed into a ubuntu container, all I had to do was to setup the http_proxy environment variable and the stack picked it up automatically like you would do normally.

Very nice!

**Comment by StefH** [comment] 2019-03-14 21:44
The documentation on `TransportType.cs` tells now (2019-03-14):

> To setup a proxy connection, please configure system default proxy. Proxy currently is supported only in  .NET 4.5.1 and higher or .NET Core 2.1 and higher.

But how to configure the system default proxy in code?

@SeanFeldman Maybe you can help?

**Comment by ErikMogensen** [comment] 2019-03-20 18:35
In the PR I just created it works with a proxy if you use code similar the code previously shown in this issue:
```
WebProxy proxyObject = new WebProxy(
    "http://<proxyserver>:<proxyport>", 
    true, 
    new string[] { "somemachine" }, 
    new NetworkCredential("<user>", "<password>"));
WebRequest.DefaultWebProxy = proxyObject;

```

**Closed** 2019-03-20 22:49 UTC
