### ISSUE TITLE
Exception "ServiceBusException: ProtocolName48545450" when sending to a topic using MSI

### ISSUE THREAD

**Issue by erick-thompson** [Azure/azure-service-bus-dotnet#411] opened 2018-01-27 00:48 UTC
I'm attempting to get MSI to work with Service Bus for sending messages to a topic from local/VS. When I have the following code:

var tokenProvider = new ManagedServiceIdentityTokenProvider();
var topicClient = new TopicClient("", topic, tokenProvider);
await topicClient.SendAsync(messages);

I get the exception "Microsoft.Azure.ServiceBus.ServiceBusException: ProtocolName48545450". The same code with a connection string works fine:

var topicClient = new TopicClient("...", topic);
await topicClient.SendAsync(messages);

I am using MSI to access ARM, so I know that VS is set up with my identity. Is there some other setup needed when using ManagedServiceIdentityTokenProvider (as opposed to AzureServiceTokenProvider)? I pulled the source, and couldn't figure out where that particular message is coming from.

Thanks,
Erick

## Versions  
- OS platform and version: Win 10
- .NET Version: Core 2
- NuGet package version or commit ID: 3.0.0-preview-01

**Comment by SeanFeldman** [comment] 2018-02-01 17:11
@ChristianWolf42 is MSI properly supported at this point in the new client?

**Comment by SeanFeldman** [comment] 2018-02-01 17:17
@erick-thompson same error if you try it with a queue?

**Comment by serkantkaraca** [comment] 2018-02-01 17:26
Can you provide full exception and the stack? I will try to repro the issue.

**Comment by ChristianWolf42** [comment] 2018-02-01 19:16
@erick-thompson and @SeanFeldman MSI is supposed to work with both the Java and the .NET clients. Please provide the exceptions / problems you are seeing and we will help.

**Comment by ChristianWolf42** [comment] 2018-02-01 19:29
@erick-thompson one clarifying question. MSI can only run from a cloud service like a web page. Windows 10 is not supported e.g.
Have you tried the basic sample from github with a web app first and then tried to port that to the new client?

**Comment by serkantkaraca** [comment] 2018-02-01 21:39
Are you running it on Server or Client OS? I thought MSI isn't enabled on Client OS.

**Comment by jtaubensee** [comment] 2018-02-01 21:54
Here is an example for KeyVault: https://azure.microsoft.com/en-us/resources/samples/app-service-msi-keyvault-dotnet/

The team that does [`Microsoft.Azure.Services.AppAuthentication`](https://www.nuget.org/packages/Microsoft.Azure.Services.AppAuthentication/) has enabled local development scenarios for MSI and KeyVault using Azure CLI.

I'm just guessing here, but I would think that this would be pretty easy to plug in to Service Bus / Event Hubs / Relay?

**Comment by jsacapdev** [comment] 2018-06-28 14:00
I am seeing the same issue but I am _not_ using MSI. Example code:

```
var builder = new ServiceBusConnectionStringBuilder("https://namespace.servicebus.windows.net", 
"mytopic", 
"mytopicauthrule", 
"myprimarkkey");
var topicClient = new TopicClient(builder);

var message = new Message(Encoding.UTF8.GetBytes("messageBody"));
await topicClient.SendAsync(message);
```

*.csproj:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <LangVersion>latest</LangVersion>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.ServiceBus" Version="3.0.2" />
  </ItemGroup>

</Project>
```

Exception Message:

`ProtocolName48545450`

**Comment by nemakam** [comment] 2018-06-29 01:02
@jsacapdev @erick-thompson  So the issue is happening because the connectionstring is `https://*`. Change that to `sb://*` and it should work.. I'll send out a fix for this soon

**Comment by jsacapdev** [comment] 2018-06-29 14:18
i can confirm that works for me. thanks.

**Closed** 2018-06-29 23:10 UTC
