### ISSUE TITLE
Calling CompleteAsync(lockToken) in SubscriptionClient.RegisterMessageHandler() throws a lock lost exception if you take longer than 10 minutes

### ISSUE THREAD

**Issue by WilliamHBonney** [Azure/azure-service-bus-dotnet#378] opened 2017-11-28 16:50 UTC
Hi, i am having an issue whereby i cannot complete a message received from SubscriptionClient.

I have tracked down the issue to MessageReciever.cs method DisposeMessagesAsync() (bascially if TryGetOpenedObject is false (because it took more than 10 minutes?) then ReceiveLinkManager.GetOrCreateAsync() makes a new ampq connection, but BeginDisposeMessage(outcome = accept) fails and throws a MessageLockLostException.

The issue is that i am the same instance, but the receivelink has changed under me.

![image](https://user-images.githubusercontent.com/19433524/33388726-9e7dd9a0-d528-11e7-8ff1-0317b52d39a2.png)

!= 

![image](https://user-images.githubusercontent.com/19433524/33388752-ae678c1c-d528-11e7-9186-ddbfa6655637.png)

Should the middle bit ":1:10:12" be ignored when comparing the owner?

Thanks
 Billy

Pushed fork with console app that produces these outputs

https://github.com/WilliamHBonney/azure-service-bus-dotnet/commit/acb85828922f715ece5e94d9c4c292eaf8450bc4

## Actual Behavior
1. Use SubscriptionClient.RegisterMessageClient() with 
    AutoComplete = false,
    MaxAutoRenewDuration = TimeSpan.FromMinutes(30),
    MaxConcurrentCalls = 1
  (lock duration is 5 minutes or 30 seconds it doesn't matter)
2. In handler do processing for 11 minutes
3. Call SubscriptionClient.CompleteAsync(message.SystemProperties.LockToken)
4. Message Lock lost exception

## Expected Behavior
1. Use SubscriptionClient.RegisterMessageClient() with 
    AutoComplete = false,
    MaxAutoRenewDuration = TimeSpan.FromMinutes(30),
    MaxConcurrentCalls = 1
  (lock duration is 5 minutes or 30 seconds it doesn't matter)
2. In handler do processing for 11 minutes
3. Call SubscriptionClient.CompleteAsync(message.SystemProperties.LockToken)
4. Message is marked as compete and removed.

This only happens if processing takes more than 10 minutes.
This doesn't happen with the QueueClient
If i change the lock duration it doesn't change the behaviour, it still only happens after 10 minutes.
If i complete processing after 9 minutes it works perfectly.
I tried increasing OperationTimeout to an hour but it didnt make any difference.
The ampq connection is closing after 10 minutes and then when another is opened it cannot dispose the TryGetOpenedObject() the BeginDisposeMessage(accept()) fails with a MessageLockLostException.
I can reproduce this every time at will.

Output of a working example (processing takes 1 minute) - ReceiverLink is kept open
![image](https://user-images.githubusercontent.com/19433524/33380590-82e2882c-d513-11e7-9270-8bcd359dd22b.png)

Output of a failing example (processing takes 11 minutes) - ReceiverLink is opened with a different id
![image](https://user-images.githubusercontent.com/19433524/33381984-6e9b3c70-d517-11e7-9ab9-285eb70718d8.png)

## Versions  
- OS platform and version: Windows 10
- .NET Version: .net standard 2.0
- NuGet package version or commit ID: AzureServiceBus 2.0.0

**Comment by nemakam** [comment] 2017-12-29 23:13
@WilliamHBonney 
1. This is by design. With amqp, the lock tokens are associated with the link through which it was received. If a connection drop happens, the links are dropped, and hence all the messages will end up throwing `MessageLockLostException`.
2. The problem that needs to be chased here is why the links are expiring. There is an auto renewal that is supposed to happen for each link which renews the link expiration time. (`ActiveClientLinkManager.cs`). If this renewal fails, then by default after 10 minutes the link will be closed by the service, and then everything else becomes by design.

Could you enable tracing on your client for provider `Microsoft-Azure-ServiceBus` and get a repro and share it?

**Comment by nemakam** [comment] 2018-01-05 01:08
@WilliamHBonney 
We have found the issue on service side and will be fixing it shortly.

**Comment by NiklasArbin** [comment] 2018-01-17 07:29
Any news on this? I am experiencing similar issues, but am in the process of trying to see what's happening. So far for messages that runs over 11 minutes the await client.CompleteAsync(message.SystemProperties.LockToken).ConfigureAwait(false) call just hangs, like an async deadlock, even though in the same method I'm doing more async work without issues.

**Comment by NiklasArbin** [comment] 2018-01-17 20:30
@nemakam This is a very serious production issue in enterprise grade software, any news on this? Last comment is 13 days old.

I've tested the 2.0 version, the 3.0.0-preview and the minor branch that is referenced above. All have the same issue.

**Comment by nemakam** [comment] 2018-01-18 01:44
@NiklasArbin 
This would likely take some more time to completely release the fix. So here's the details of the issue:

At amqp level, we create a `ReceivingLink` where the ASB Client is the receiver of the messages. On that link, only `complete/abandon/deadletter/defer` operations are possible outside of receiving the message itself. 
For message lock renewal, we create a separate `RequestResponseLink` which can handle other complex operations as well like ReceiveDeferredMessage/Sessions etc. 
On broker, we have an idle timeout of 10 minutes for a link. If a link is idle for more than 10 minutes we close it. The receiveAsync() and completeAsync() happens on the receiving link but RenewAsync() happens on a separate link. Hence after 10 minutes the original link closes due to inactivity. 

So based on this, for immediate resolutions, see if you could keep the link active with dummy operations? (including receive and abandon).

**Comment by NiklasArbin** [comment] 2018-01-18 07:57
@nemakam Tried calling CompleteAsync and AbandonAsync with an invalid message Guid every 1 minute to keep the link alive, swallowing the exceptions, but it didn't work.

How is this issue prioritized in the ASB team? How do you rate it's severity?

**Comment by NiklasArbin** [comment] 2018-01-19 07:10
@nemakam Any updates? Just to be clear, not only is the message not able to complete after 10 minutes. The CompleteAsync calls enters some kind of async deadlock which in turns halts processing on the QueueReader when MaxConcurrent is reached since the semaphore is not released. And in the case of long running processes it's common to set MaxConcurrent to a low value.

**Comment by nemakam** [comment] 2018-01-19 20:37
@NiklasArbin 
This requires service side changes to the way we handle renew() in AMQP. Rolling out a service side changes definitely take time since it goes through lot of testing and we need to follow safe deployment process (ensuring not deploying everywhere at the same time).
Meanwhile, I can only suggest some hacky workarounds.
1. ReceiveAsync() and Abandon() is the easiest way. When you abandon with an invalid GUID, the client itself throws MessageLockLostException instead of going all the way to the service. So from service perspective, the link is still idle. One way to achieve this would be to increase the delivery count on the queue, do an actual Receive() followed by Abandon(). Since idle timeout is 10 mins, you'll have to do this once every 8-9 mins. 
2. If you are not hard bound to .net standard, you could consider temporarily using our full framework client (old client - [Nuget](https://www.nuget.org/packages/WindowsAzure.ServiceBus/)) and switch to using `NetMessaging` transport instead of `amqp` which doesn't have the same issue.

**Comment by nemakam** [comment] 2018-01-19 23:46
Also, till the time this is fixed, if you get into a situation where the processing is stuck, you should consider closing and recreating the QueueClient.

**Comment by NiklasArbin** [comment] 2018-01-23 19:34
@nemakam 
1. Not sure I think this is feasible in a production environment, then we'd need to add logic to all message handlers to detect dummy messages, the deadletter count is there for a reason and usually for long running operation they should not be autoretried.

2. Bound to net standard, so no

Not really sure of an elegant way of detecting async deadlocks, if that's at all possible. My simple code in the issue that was closed actually deadlocks every time. A MessageLockLostException I could have handled.

For now we're abandoning the ASB since we judge this issue to be that severe. In the meantime while having this discussion we've added support for another messaging provider to our own bus framwork.

If I was on the ASB team, the question I would talk about in the next retro would be how this was not identified as critical and have been left 19 days since you identified the behavior.

**Comment by nemakam** [comment] 2018-02-13 00:13
Client side changes are present in #420. Service side changes are yet to be rolled out.

**Comment by samcook** [comment] 2018-06-18 13:41
Is there any update on when the server side of this fix will be rolled out? This issue makes using the AMQP transport (and thus this version of the library), unusable for us currently.

**Comment by samcook** [comment] 2018-06-18 19:44
In which case the fix doesn't work (or I'm doing something wrong).

Here's some sample code: https://gist.github.com/samcook/b16381e38425aa2aa911582ee51d0cf9

When I run it, this is what eventually happens, if the message handler takes > 10 minutes:
```
18/06/2018 20:22:33 Press enter to add message to queue
18/06/2018 20:22:33 Received message, sleeping for 00:10:10
18/06/2018 20:32:43 Finished sleeping
18/06/2018 20:32:44 Exception: Microsoft.Azure.ServiceBus.MessageLockLostException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue, or was received by a different receiver instance.
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<DisposeMessagesAsync>d__100.MoveNext() in C:\source\azure-service-bus-dotnet\src\Microsoft.Azure.ServiceBus\Core\MessageReceiver.cs:line 1431
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__18.MoveNext() in C:\source\azure-service-bus-dotnet\src\Microsoft.Azure.ServiceBus\RetryPolicy.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__18.MoveNext() in C:\source\azure-service-bus-dotnet\src\Microsoft.Azure.ServiceBus\RetryPolicy.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<CompleteAsync>d__69.MoveNext() in C:\source\azure-service-bus-dotnet\src\Microsoft.Azure.ServiceBus\Core\MessageReceiver.cs:line 538
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.MessageReceivePump.<CompleteMessageIfNeededAsync>d__16.MoveNext() in C:\source\azure-service-bus-dotnet\src\Microsoft.Azure.ServiceBus\MessageReceivePump.cs:line 216
```

Using `Microsoft.Azure.ServiceBus` `3.0.2`

**Comment by nemakam** [comment] 2018-06-26 00:43
@samcook 
Looks like there was a regression in the service after the fix was deployed for non-partitioned entities. The fix has been checked-in. It will be released in a few days...
The regression was only for non-partitioned entities. This should work for partitioned-entities.

**Comment by Zebusch** [comment] 2018-08-07 11:00
I am not sure if i am doing something wrong but i get the same error. Using the samples and trying some different configuration i always get problems with the second message. The first is fine becuase the lock expiration is OK. The second message i recieve will have the same expiration as the first which leads to the exception if the processing of the first message exceeds the time of LockDuration. Not sure how to get around this? In the "old" .NET client there is a method that can be used to renew a lock. The problem for me is that the lock has already expired when i either complete the message or try to renew it. Do i need to re-instatiate the MessageReceiver for every message rather than doing like the examples do with one instance and then just:

`messageReceiver.RegisterMessageHandler(
                async (message, token) =>
                {`

**Comment by nemakam** [comment] 2018-08-09 22:17
Service has been patched

**Closed by nemakam** 2018-08-09 22:17 UTC
Labels: bug, service side
